Add support for combining --merge and --symmetric
Signed-off-by: Mattias Andrée <m@maandree.se>

diff --git a/t/invalid-option-combinations b/t/invalid-option-combinations
--- a/t/invalid-option-combinations
+++ b/t/invalid-option-combinations
@@ -4,66 +4,58 @@
 printf '%s\n' text > file
 cp -- file file.expected
 
-error --merge --select-head file
-error --select-head --merge file
-error --merge --select-tail file
-error --select-tail --merge file
-error --select-head --select-tail file
-error --select-tail --select-head file
-error --merge --select-head --select-tail file
-error --merge --select-tail --select-head file
-error --select-head --merge --select-tail file
-error --select-head --select-tail --merge file
-error --select-tail --merge --select-head file
-error --select-tail --select-head --merge file
-error --symmetric --merge file
-error --merge --symmetric file
-error --symmetric --select-head file
-error --select-head --symmetric file
-error --symmetric --select-tail file
-error --select-tail --symmetric file
-error --symmetric --merge --select-head file
-error --symmetric --select-head --merge file
-error --symmetric --merge --select-tail file
-error --symmetric --select-tail --merge file
-error --symmetric --select-head --select-tail file
-error --symmetric --select-tail --select-head file
-error --merge --symmetric --select-head file
-error --select-head --symmetric --merge file
-error --merge --symmetric --select-tail file
-error --select-tail --symmetric --merge file
-error --select-head --symmetric --select-tail file
-error --select-tail --symmetric --select-head file
-error --merge --select-head --symmetric file
-error --select-head --merge --symmetric file
-error --merge --select-tail --symmetric file
-error --select-tail --merge --symmetric file
-error --select-head --select-tail --symmetric file
-error --select-tail --select-head --symmetric file
-error --symmetric --merge --select-head --select-tail file
-error --symmetric --merge --select-tail --select-head file
-error --symmetric --select-head --merge --select-tail file
-error --symmetric --select-head --select-tail --merge file
-error --symmetric --select-tail --merge --select-head file
-error --symmetric --select-tail --select-head --merge file
-error --merge --symmetric --select-head --select-tail file
-error --merge --symmetric --select-tail --select-head file
-error --select-head --symmetric --merge --select-tail file
-error --select-head --symmetric --select-tail --merge file
-error --select-tail --symmetric --merge --select-head file
-error --select-tail --symmetric --select-head --merge file
-error --merge --select-head --symmetric --select-tail file
-error --merge --select-tail --symmetric --select-head file
-error --select-head --merge --symmetric --select-tail file
-error --select-head --select-tail --symmetric --merge file
-error --select-tail --merge --symmetric --select-head file
-error --select-tail --select-head --symmetric --merge file
-error --merge --select-head --select-tail --symmetric file
-error --merge --select-tail --select-head --symmetric file
-error --select-head --merge --select-tail --symmetric file
-error --select-head --select-tail --merge --symmetric file
-error --select-tail --merge --select-head --symmetric file
-error --select-tail --select-head --merge --symmetric file
+all_permutations () {
+	if test $# = 2; then
+		error "$1" "$2" file
+		error "$2" "$1" file
+	elif test $# = 3; then
+		error "$1" "$2" "$3" file
+		error "$1" "$3" "$2" file
+		error "$2" "$1" "$3" file
+		error "$2" "$3" "$1" file
+		error "$3" "$1" "$2" file
+		error "$3" "$2" "$1" file
+	elif test $# = 4; then
+		error "$1" "$2" "$3" "$4" file
+		error "$1" "$2" "$4" "$3" file
+		error "$1" "$3" "$2" "$4" file
+		error "$1" "$3" "$4" "$2" file
+		error "$1" "$4" "$2" "$3" file
+		error "$1" "$4" "$3" "$2" file
+		error "$2" "$1" "$3" "$4" file
+		error "$2" "$1" "$4" "$3" file
+		error "$2" "$3" "$1" "$4" file
+		error "$2" "$3" "$4" "$1" file
+		error "$2" "$4" "$1" "$3" file
+		error "$2" "$4" "$3" "$1" file
+		error "$3" "$1" "$2" "$4" file
+		error "$3" "$1" "$4" "$2" file
+		error "$3" "$2" "$1" "$4" file
+		error "$3" "$2" "$4" "$1" file
+		error "$3" "$4" "$1" "$2" file
+		error "$3" "$4" "$2" "$1" file
+		error "$4" "$1" "$2" "$3" file
+		error "$4" "$1" "$3" "$2" file
+		error "$4" "$2" "$1" "$3" file
+		error "$4" "$2" "$3" "$1" file
+		error "$4" "$3" "$1" "$2" file
+		error "$4" "$3" "$2" "$1" file
+	else
+		printf 'Error in test case: all_permutations was given %s arguments\n' "$#" >&2
+		exit 99;
+	fi
+}
+
+all_permutations --select-head --select-tail
+all_permutations --merge --select-head
+all_permutations --merge --select-tail
+all_permutations --merge --select-head --select-tail
+all_permutations --symmetric --select-head
+all_permutations --symmetric --select-tail
+all_permutations --symmetric --select-head --select-tail
+all_permutations --merge --symmetric --select-head
+all_permutations --merge --symmetric --select-tail
+all_permutations --merge --symmetric --select-head --select-tail
 
 error --unknown-option file
 error '-$' file
